[font]
size = 12.0

[font.normal]
family = "FiraCodeNerdFont" # "MesloLGS Nerd Font"

[keyboard]
bindings = [
  { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" },
  { key = "М", mods = "Control|Shift", action = "Paste" }, # [ru] 'М' -> [en] 'V'
  { key = "С", mods = "Control|Shift", action = "Copy" },  # [ru] 'С' -> [en] 'C'
]
