[font]
size = 14.0
normal = { family = "MesloLGS Nerd Font" }

[keyboard]
bindings = [
  { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" },
  # Copy/paste with [ru]ssian keyboard layout
  { key = "ะ", mods = "Control|Shift", action = "Paste" },
  { key = "ะก", mods = "Control|Shift", action = "Copy" },
  # Extended keys
  { key = "Return", mods = "Shift",         chars = "\u001B[13;2u" },
  { key = "Return", mods = "Control",       chars = "\u001B[13;5u" },
  { key = "Return", mods = "Control|Shift", chars = "\u001B[13;6u" },
  { key = "Space", mods = "Control", chars = "\u001B[32;5u" },
  { key = "Tab", mods = "Shift",         chars = "\u001B[9;2u" },
  { key = "Tab", mods = "Control",       chars = "\u001B[9;5u" },
  { key = "Tab", mods = "Control|Shift", chars = "\u001B[9;6u" },
  { key = "h", mods = "Control|Shift", chars = "\u001B[72;6u" },
  { key = "j", mods = "Control|Shift", chars = "\u001B[74;6u" },
  { key = "k", mods = "Control|Shift", chars = "\u001B[75;6u" },
  { key = "l", mods = "Control|Shift", chars = "\u001B[76;6u" },
  { key = "n", mods = "Control|Shift", chars = "\u001B[78;6u" },
  { key = "p", mods = "Control|Shift", chars = "\u001B[80;6u" },
  { key = "Key0", mods = "Control", chars = "\u001b[48;5u" },
  { key = "Key1", mods = "Control", chars = "\u001b[49;5u" },
  { key = "Key2", mods = "Control", chars = "\u001b[50;5u" },
  { key = "Key3", mods = "Control", chars = "\u001b[51;5u" },
  { key = "Key4", mods = "Control", chars = "\u001b[52;5u" },
  { key = "Key5", mods = "Control", chars = "\u001b[53;5u" },
  { key = "Key6", mods = "Control", chars = "\u001b[54;5u" },
  { key = "Key7", mods = "Control", chars = "\u001b[55;5u" },
  { key = "Key8", mods = "Control", chars = "\u001b[56;5u" },
  { key = "Key9", mods = "Control", chars = "\u001b[57;5u" },
]
